# Generated by Django 5.2.16 on 2026-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
